### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by bowbahdoe** [aymanbagabas/go-osc52#2]
```go
func (s Sequence) seqEnd() string {
	switch s.mode {
	case TmuxMode:
		// Terminate the tmux escape sequence.
		return "\x1b\\"
	case ScreenMode:
		// Write the end of a DCS sequence.
		return "\x1b\x5c"
	default:
		return ""
	}
}
```

Not a bug, but both branches will have the same content. `\x5c` is equivalent to a backslash. So is `\\`.

Noticed while [porting the code to java](https://github.com/bowbahdoe/osc52).

**Comment by aymanbagabas** [comment]
@bowbahdoe good catch! This is fixed in https://github.com/aymanbagabas/go-osc52/commit/5c9b696c9b6c78c88f0bed2178029f2de2458b0e
